Allow injecting user synchronization modules
chipsalliance/Cores-VeeR-EL2 pull request #56
Opened 2023-02-15 15:34 UTC by mkurc-ant

This PR allows injection of modules containing synchronization flip-flops.

The config script allows to set additional parameters which end up in code as capitalized defines:

tech_specific_rv_sync - enables usage of the user module
user_rv_sync - specifies the module name

**The PR is based on https://github.com/chipsalliance/Cores-VeeR-EL2/pull/54 and should be reviewed and merged after it.**

2023-04-25 22:15 UTC, varuns-nvidia commented
Hi @mkurc-ant , what is the status of this issue?

2023-04-26 07:25 UTC, mkurc-ant commented
Hi @varuns-nvidia. This PR is ready but marked as draft as it is based on https://github.com/chipsalliance/Cores-VeeR-EL2/pull/54 (shared codebase) which has not yet been reviewed.

2023-05-29 11:55 UTC, mkurc-ant commented
@varuns-nvidia FYI this is ready for review.

2023-05-29 17:59 UTC, nstewart-amd requested changes
The user_rv_sync placeholder module should not contain an "initial" block.

The user_rv_sync module should not be multi-bit width, since it has no synchronization qualifiers for multi-bit signal synchronization.

Recommend user_rv_sync is single bit in/out.
Recommend user_rv_sync instantiates rvdff behavioural flop model from existing beh_lib.sv.

2023-05-30 08:36 UTC, mkurc-ant commented
@nstewart-amd I changed the required user synchronizer cell model to be 1-bit and without any initial blocks. I left the behavioral code in `design/dmi/dmi_jtag_to_core_sync.v` as it was like that before my changes (It would be best to tackle this in a separate PR if needed). I also left the behavioral code in `user_rv_sync` as it is not used by default. When enabled it is used only in the testbench.

2024-10-22 13:28 UTC, closed without merging